site_name: Two Pi Academy
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - tables

theme:
  name: material
  logo: assets/two-pi-academy-logo.png
  favicon: assets/two-pi-academy-logo.png
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.sections
    - navigation.footer
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Class-11 Maths:
     - Trigonometry:
        - maths/trigonometry/index.md
        - Formulas:
          - maths/trigonometry/formulas/angle-measurement.md
          - maths/trigonometry/formulas/trigonometric-ratios.md
          - maths/trigonometry/formulas/trigonometric-functions-for-compound-angles.md
        - Tests:
          - maths/trigonometry/tests/test-1.md
          - maths/trigonometry/tests/test-2.md
          - maths/trigonometry/tests/test-final.md
     - Complex Numbers:
        - maths/complex-numbers/index.md
        - Formulas:
          - maths/complex-numbers/formulas/arithmetic-operations.md
          - maths/complex-numbers/formulas/modulus-and-conjugate.md
        - Tests:
          - maths/complex-numbers/tests/test-final.md
  - Class-11 Physics:
    - Motion in a Straight Line:
      - physics/motion-in-straight-line/index.md
      - physics/motion-in-straight-line/introduction.md
      - physics/motion-in-straight-line/velocity-and-acceleration.md


extra:
  generator: false
  social:
    - icon: fontawesome/brands/youtube 
      link: https://youtube.com/@twopiacademy

plugins:
  - search

copyright: Copyright &copy; 2024 - 2025 Two Pi Academy


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css