site_name: Two Pi Academy
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer

extra:
  generator: false
  social:
    - icon: fontawesome/brands/youtube 
      link: https://youtube.com/@twopiacademy

copyright: Copyright &copy; 2024 - 2025 Two Pi Academy

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
