[project]
name = "two-pi-academy"
version = "0.1.0"
description = ""
authors = [{ name = "Tejesh Kaliki", email = "tejesh.kaliki@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material>=9.6.13",
]
